services:
  db:
    image: postgres:17
    container_name: nest_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Abcd@1234
      POSTGRES_DB: ellatech
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: nest_api
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: Abcd@1234
      DB_NAME: ellatech

    ports:
      - '3000:3000'
    command: sh -c "sleep 10 && npm run start:dev"

volumes:
  db_data:
